// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMS4Gwzpyy_kYkew8G4wZ-MxbdrRoiW74',
    appId: '1:922468499334:web:9ce81a80e647b80e3a7607',
    messagingSenderId: '922468499334',
    projectId: 'threads-clone-5d3f5',
    authDomain: 'threads-clone-5d3f5.firebaseapp.com',
    storageBucket: 'threads-clone-5d3f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7xmhxz1wmkVSg1arz1GNTSjjLyf9BwBY',
    appId: '1:922468499334:android:33373775adacd34d3a7607',
    messagingSenderId: '922468499334',
    projectId: 'threads-clone-5d3f5',
    storageBucket: 'threads-clone-5d3f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcpu81yjar6iRqyt-fYJLQCvatpG2iXc4',
    appId: '1:922468499334:ios:64ed39c26fbcc3093a7607',
    messagingSenderId: '922468499334',
    projectId: 'threads-clone-5d3f5',
    storageBucket: 'threads-clone-5d3f5.firebasestorage.app',
    iosBundleId: 'com.example.threadsClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcpu81yjar6iRqyt-fYJLQCvatpG2iXc4',
    appId: '1:922468499334:ios:64ed39c26fbcc3093a7607',
    messagingSenderId: '922468499334',
    projectId: 'threads-clone-5d3f5',
    storageBucket: 'threads-clone-5d3f5.firebasestorage.app',
    iosBundleId: 'com.example.threadsClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMS4Gwzpyy_kYkew8G4wZ-MxbdrRoiW74',
    appId: '1:922468499334:web:0b05a209a89f93bb3a7607',
    messagingSenderId: '922468499334',
    projectId: 'threads-clone-5d3f5',
    authDomain: 'threads-clone-5d3f5.firebaseapp.com',
    storageBucket: 'threads-clone-5d3f5.firebasestorage.app',
  );

}